/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 97e832a043228f515ca1e8faae8f2a09)
interface __BaseEnv_Env {
	VAULTWARDEN_BACKUPS: R2Bucket;
	REMOTE_WORKFLOW_SERVER: Fetcher;
	REMOTE_WORKFLOW_PATH: "/vaultwarden-backup";
	REMOTE_WORKFLOW_REGISTRATION: Workflow<Parameters<import("./src/relay").RemoteWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/relay");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REMOTE_WORKFLOW_PATH">> {}
}
